name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Unit Test
      run: npm run coverage

    - name: Integration Test
      run: npm run coverage

    - name: End-to-End Test
      run: npx playwright test endtoend.test.js
